---
- #hosts: cr173
  hosts: sta199
  become: yes
  vars_prompt:
    - name: course
      prompt: Enter the course name
    - name: runner_token
      prompt: Enter the GH runner token
    - name: org_url
      prompt: Enter the url for your GH organization
  roles:
  - gh-runners