---
- hosts: sta199
  become: yes
  vars_prompt:
    - name: course
      prompt: Enter the course name
      private: no
    - name: runner_token
      prompt: Enter the GH runner token
      private: yes
    - name: org_url
      prompt: Enter the url for your GH organization
      private: no
    - name: runner_n
      prompt: Enter the number of runners
      default: "4"
      private: no
  roles:
  - gh-runners