[sta199]
#geometry2.stat.duke.edu
vcm-52470.vm.duke.edu
vcm-52472.vm.duke.edu
vcm-52510.vm.duke.edu


[sta199:vars]
ansible_user=cr173
runner_base_dir=/data

[cr173]
rapid-1733.vm.duke.edu

[cr173:vars]
ansible_user=rapiduser

[mon]
mon.stat.duke.edu

[mon:vars]
ansible_user=rundel

[mine]
rapid-2745.vm.duke.edu

[mine:vars]
ansible_user=rapiduser
runner_base_dir=/data